# (APPENDIX) Appendix {-}

# Variance/covariance rules {#appendix-rules}



-  [**Rule 1**](./variance.html#Rule1)

If $C$ is constant, then

$$
Var\left(C\right) = 0
$$

-  [**Rule 2**](./variance.html#Rule2)

If $X_{1}$ and $X_{2}$ are independent, then

$$
Var\left(X_{1} + X_{2}\right) =
Var\left(X_{1}\right) + Var\left(X_{2}\right)
$$

Consequence of [**Rule 1**](./variance.html#Rule1) and [**Rule 2**](./variance.html#Rule2):

$$
Var\left(X + C\right) = Var\left(X\right)
$$

-  [**Rule 3**](./variance.html#Rule3)

If $X_{1}$ and $X_{2}$ are independent, then

$$
Var\left(X_{1} - X_{2}\right) =
Var\left(X_{1}\right) + Var\left(X_{2}\right)
$$

-  [**Rule 4**](./variance.html#Rule4)

If $a$ is any number, 

$$
Var\left(aX\right) = a^2 Var\left(X\right)
$$
Related to this rule is the corresponding one for standard deviations:

$$
SD\left(aX\right) = \left| a \right| SD\left(X\right)
$$

-  [**Rule 5**](./covariance.html#Rule5)

$$
Cov(X, X) = Var(X)
$$

-  [**Rule 6**](./covariance.html#Rule6)

$$
Cov\left(X_{1}, X_{2}\right) = Cov\left(X_{2}, X_{1}\right)
$$

-  [**Rule 7**](./covariance.html#Rule7)

If $C$ is constant, then

$$
Cov\left(X, C\right) = 0
$$

-  [**Rule 8**](./covariance.html#Rule8)

$$
Cov\left(X_{1} + X_{2}, X_{3}\right) = Cov\left(X_{1}, X_{3}\right) + Cov\left(X_{2}, X_{3}\right)  
$$

-  [**Rule 9**](./covariance.html#Rule9)

$$
Cov\left(X_{1} - X_{2}, X_{3}\right) = Cov\left(X_{1}, X_{3}\right) - Cov\left(X_{2}, X_{3}\right)  
$$

Consequence of [**Rule 6**](./covariance.html#Rule6), [**Rule 8**](./covariance.html#Rule8), and [**Rule 9**](./covariance.html#Rule9):

$$
Cov\left(X_{1}, X_{2} \pm X_{3}\right) = Cov\left(X_{1}, X_{2}\right) \pm Cov\left(X_{1}, X_{3}\right)  
$$

-  [**Rule 10**](./covariance.html#Rule10)

If $a$ is any number, 

$$
Cov\left(a X_{1}, X_{2}\right) = a Cov\left(X_{1}, X_{2}\right) =  Cov\left(X_{1}, a X_{2}\right)  
$$

-  [**Rule 11**](./covariance.html#Rule11)

If $X_{1}$ and $X_{2}$ are independent, then

$$
Cov\left(X_{1}, X_{2}\right) = 0
$$

-  [**Rule 12**](./covariance.html#Rule12)

For *any* two variables $X_{1}$ and $X_{2}$:

$$
Var(aX_{1} + bX_{2}) = 
    a^2Var(X_{1}) + b^2Var(X_{2}) + 2abCov(X_{1}, X_{2})
$$

For any three variables $X_{1}$, $X_{2}$, and $X_{3}$:

\begin{align}
Var(aX_{1} + bX_{2} + cX_{3}) &= 
    a^2Var(X_{1}) + b^2Var(X_{2}) + c^2Var(X_{3}) \\
    & \quad + 2abCov(X_{1}, X_{2}) \\
    & \quad + 2acCov(X_{1}, X_{3}) \\
    & \quad + 2bcCov(X_{2}, X_{3})
\end{align}

This can be extended to any number of variables. Each variance appears with a coefficient squared and each pair of variables gets a covariance term with 2 times the product of the corresponding variable coefficients.


# LISREL notation {#appendix-lisrel}
